baseURL = "https://cssc.asn.au"
title = "CSSC"
theme = "gokarna"
languageCode = "en-au"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
image = "/branding/cssc_logo_256.png"

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Computer Science Students' Club"
  description = "Computer Science Students' Club"
  avatarURL = "/branding/cssc_logo.svg"
  avatarAltText = "Avatar"
  avatarTextURL = "/branding/cssc_text.svg"
  heroURL = "/images/hero.png"
  heroAltText = "Hero"
  metaKeywords = ["Computer Science Students' Club", "CSSC", "UWA", "CSSC UWA"]

  # Home
  welcome = """WELCOME TO THE
    COMPUTER SCIENCE
    STUDENTS' CLUB"""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 2

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 3


  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 4


  [[menu.main]]
    name = "Sign Up"
    url = "/sign-up/"
    weight = 5


  [[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 6


  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/csscuwa"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true
